# Code directory
src: "src"

# Containers
sisana_container: "docker://rtpop/sisana:0.0.2" # remember to change once container is made
eland_container: "container_name"
analysis_container: "container_name"

# Directories
data_dir: "data"
output_dir: "output" # this will be a parent directory for different runs
sisana_dir: "sisana"
src_dir: "src"
eland_dir: "eland"

# Input files
sisana_config: "params.yml"
exp_file: "exp_file_name"
motif_prior_file: "motif_prior_names_2024"
ppi_prior_file: "ppi_prior_2024"

# bihidef params
max_resolution: 5 # the maximum resolution parameter for bihidef
# a multiplier for the maximum number of communities passed to condor. not implemented yet
# this will be passed as the "c" parameter in condor, but I haven't figured out how I want to do it yet
# my idea is to pass a multiplier and then within bihidef, for each resolution, do the same calculation
# that is default in condor, but instead of the default condor multiplier, use this multiplier
max_communities: 2 

# Other params
delimiter: "\t" # delimiter for input & output files