# Code directory
src: "src"

# Containers
sisana_container: "container_name" # remember to change once container is made
eland_container: "container_name"
analysis_container: "container_name"

# Directories
data_dir: "data"
output_dir: "output" # this will be a parent directory for different runs
sisana_dir: "sisana"
src_dir: "src"
eland_dir: "eland"

# Input files
sisana_config: "params.yml"
exp_file: "exp_file_name"
motif_prior_file: "motif_prior_names_2024"
ppi_prior_file: "ppi_prior_2024"

# Other params
delimiter: "\t" # delimiter for input & output files