##------------##
## Containers ##
##------------##
python_container: "docker://rtpop/eland-run:0.0.10"
analysis_container: "docker://rtpop/eland-downstream:0.0.1"

##-------------##
## Directories ##
##-------------##  
src: "src" # Code directory
data_dir: "data"
output_dir: "output" # this will be a parent directory for different runs
sisana_dir: "sisana"
src_dir: "src"
eland_dir: "eland"

##-------------##
## Input files ##
##-------------##
sisana_config: "params.yml"
exp_file: "exp_no_header"
motif_prior_file: "motif_prior_names_2024"
ppi_prior_file: "ppi_prior_2024"

##--------------------##
## BiHiDef parameters ##
##--------------------##
max_communities: 2 # multiplier for the maximum number of communities passed to condor
max_resolution: 5 # the maximum resolution parameter for bihidef
min_resolution: 0.001 # the minimum resolution parameter for bihidef (not used in the snakemake atm)
resolution_step: 0.001 # the step size for the resolution parameter (not used in the snakemake atm)
target_tag: "gene"
regulator_tag: "TF"

# the minimum and maximum number of genes in a community
min_genes: 10
max_genes: 200

##-------------------##
## Sambar parameters ##
##-------------------##

##------------------##
## Other parameters ##
##------------------##
delimiter: "," # delimiter for input & output files