# Stage 1: Preprocess data to format for next stage
# example: sisana preprocess -p params.yml
preprocess:
  exp_file: ./uterus/gtex_uterus_exp.tsv # Path to expression file, which MUST CONTAIN A HEADER
  motif_file: ../ELAND/data/motif_prior_names_2024.tsv # path to motif file
  ppi_file: ../ELAND/data/ppi_prior_2024.tsv # path to PPI file
  number: 5 # number of samples a gene must be expressed in
  outdir: ./output/preprocess # The directory to save the output to

# Stage 2: Reconstruct networks and calculate degrees
# example: sisana generate -p params.yml
generate:
  processed_paths: ./tmp/processed_data_paths.yml # Path to yaml file containing the location of the processed data files
  method: panda # Which method to use, either "panda" to run just PANDA or "lioness", which runs PANDA first, then LIONESS
  outdir: ./output/network/ # output directory

  # The following commands are used if you specified "lioness" for the method arg
  compute: cpu # Whether to use "gpu" or "cpu" for computing LIONESS networks
  ncores: 20 # Number of cores to use for calculating LIONESS networks. Must be less than or equal to the number of samples
